#define CONFIG_CS_GPIO 18
#define CONFIG_RST_GPIO 14
#define CONFIG_MISO_GPIO 19
#define CONFIG_MOSI_GPIO 27
#define CONFIG_SCK_GPIO 5
#define CONFIG_DIO0_GPIO 26

#define CONFIG_FREERTOS_HZ 100
#define VSPI_HOST SPI3_HOST